package io.github.cat.fabricobf;

import io.github.cat.fabricobf.core.ObfuscationConfig;
import io.github.cat.fabricobf.core.ObfuscationEngine;
import io.github.cat.fabricobf.core.ObfuscationResult;
import io.github.cat.fabricobf.testutil.RandomJarGenerator;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.tree.ClassNode;

import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.jar.JarFile;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive randomised-JAR obfuscation tests.
 *
 * <p>Each variant is generated by {@link RandomJarGenerator#generateVariant}, then
 * processed by {@link ObfuscationEngine}, and the resulting JAR is checked for:
 * <ul>
 *   <li>physical existence</li>
 *   <li>parse-clean bytecode (ASM ClassReader)</li>
 *   <li>loadability (URLClassLoader)</li>
 *   <li>absence of {@code [VERIFY_PARSE_ERROR]} warnings</li>
 * </ul>
 */
class RandomJarObfuscationTest {

    /** Shared temporary directory – injected once per test class instance. */
    @TempDir
    Path tempDir;

    // -------------------------------------------------------------------------
    // Helper – run obfuscation and return the result
    // -------------------------------------------------------------------------

    private ObfuscationResult obfuscate(ObfuscationConfig config) throws Exception {
        return new ObfuscationEngine().run(config);
    }

    // -------------------------------------------------------------------------
    // Helper – assert the output JAR can be parsed by ASM without errors
    // -------------------------------------------------------------------------

    private void assertNoClassParseErrors(Path jar) throws Exception {
        try (JarFile jf = new JarFile(jar.toFile())) {
            var entries = jf.entries();
            while (entries.hasMoreElements()) {
                var entry = entries.nextElement();
                if (!entry.getName().endsWith(".class")) continue;

                byte[] bytes;
                try (var is = jf.getInputStream(entry)) {
                    bytes = is.readAllBytes();
                }

                // Let ASM parse the class – this will throw if bytecode is malformed.
                ClassReader cr = new ClassReader(bytes);
                ClassNode cn = new ClassNode();
                cr.accept(cn, ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
            }
        }
    }

    // -------------------------------------------------------------------------
    // Helper – assert every class in the output JAR can be loaded at runtime
    // -------------------------------------------------------------------------

    private void assertAllClassesLoadable(Path jar) throws Exception {
        List<String> failures = new ArrayList<>();

        try (URLClassLoader cl = new URLClassLoader(
                new java.net.URL[]{jar.toUri().toURL()},
                ClassLoader.getPlatformClassLoader());
             JarFile jf = new JarFile(jar.toFile())) {

            var entries = jf.entries();
            while (entries.hasMoreElements()) {
                var entry = entries.nextElement();
                String name = entry.getName();

                if (!name.endsWith(".class")) continue;

                // Skip classes in the default package (no '/' before '.class')
                if (!name.contains("/")) continue;

                // Convert JAR path → binary class name
                String binaryName = name
                        .substring(0, name.length() - ".class".length())
                        .replace('/', '.');

                try {
                    cl.loadClass(binaryName);
                } catch (Exception | LinkageError e) {
                    failures.add(binaryName + " → " + e.getClass().getSimpleName() + ": " + e.getMessage());
                }
            }
        }

        if (!failures.isEmpty()) {
            fail("Failed to load " + failures.size() + " class(es) from " + jar + ":\n"
                    + String.join("\n", failures));
        }
    }

    // -------------------------------------------------------------------------
    // Helper – assert no [VERIFY_PARSE_ERROR] warnings in the result
    // -------------------------------------------------------------------------

    private void assertNoVerifyParseErrors(ObfuscationResult result, int variantId) {
        List<String> errors = result.warnings().stream()
                .filter(w -> w.contains("[VERIFY_PARSE_ERROR]"))
                .toList();

        if (!errors.isEmpty()) {
            fail("Variant " + variantId + " produced " + errors.size()
                    + " [VERIFY_PARSE_ERROR] warning(s):\n"
                    + String.join("\n", errors));
        }
    }

    // -------------------------------------------------------------------------
    // Helper – print any bug-indicator warnings (non-fatal, informational)
    // -------------------------------------------------------------------------

    private void printBugWarnings(ObfuscationResult result, String label) {
        result.warnings().stream()
                .filter(w -> w.startsWith("[WRITE_ERROR]") || w.startsWith("[TRANSFORM_ERROR]"))
                .forEach(w -> System.err.println("[BUG in " + label + "] " + w));
    }

    // =========================================================================
    // Test 1 – Aggressive mode
    // =========================================================================

    @ParameterizedTest
    @ValueSource(ints = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19})
    void allVariantsLoadAfterAggressiveObfuscation(int variantId) throws Exception {
        Path input  = tempDir.resolve("in_"  + variantId + ".jar");
        Path output = tempDir.resolve("out_aggressive_" + variantId + ".jar");

        new RandomJarGenerator().generateVariant(variantId, input);

        // aggressive mode: renameClasses=true, stringEncrypt=true, aggressive=true
        ObfuscationConfig config = new ObfuscationConfig(
                input, output,
                42L,        // seed
                false,      // (reserved / keepDebug)
                List.of(),  // exclusions
                true,       // renameClasses
                true,       // stringEncrypt
                true,       // aggressive
                false,      // max
                false,      // ultra
                false,      // insane
                false       // (reserved)
        );

        ObfuscationResult result = obfuscate(config);

        assertTrue(Files.exists(output),
                "Output JAR must exist for variant " + variantId);

        assertNoClassParseErrors(output);
        assertAllClassesLoadable(output);
        assertNoVerifyParseErrors(result, variantId);
        printBugWarnings(result, "aggressive/variant-" + variantId);
    }

    // =========================================================================
    // Test 2 – Max mode
    // =========================================================================

    @ParameterizedTest
    @ValueSource(ints = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19})
    void allVariantsLoadAfterMaxObfuscation(int variantId) throws Exception {
        Path input  = tempDir.resolve("in_"  + variantId + ".jar");
        Path output = tempDir.resolve("out_max_" + variantId + ".jar");

        new RandomJarGenerator().generateVariant(variantId, input);

        // max mode
        ObfuscationConfig config = new ObfuscationConfig(
                input, output,
                99L,
                false,
                List.of(),
                true,   // renameClasses
                true,   // stringEncrypt
                false,  // aggressive
                true,   // max
                false,  // ultra
                false,  // insane
                false
        );

        ObfuscationResult result = obfuscate(config);

        assertTrue(Files.exists(output),
                "Output JAR must exist for variant " + variantId);

        assertNoClassParseErrors(output);
        assertAllClassesLoadable(output);
        assertNoVerifyParseErrors(result, variantId);
        printBugWarnings(result, "max/variant-" + variantId);
    }

    // =========================================================================
    // Test 3 – Ultra mode
    // =========================================================================

    @ParameterizedTest
    @ValueSource(ints = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19})
    void allVariantsLoadAfterUltraObfuscation(int variantId) throws Exception {
        Path input  = tempDir.resolve("in_"  + variantId + ".jar");
        Path output = tempDir.resolve("out_ultra_" + variantId + ".jar");

        new RandomJarGenerator().generateVariant(variantId, input);

        // ultra mode
        ObfuscationConfig config = new ObfuscationConfig(
                input, output,
                777L,
                false,
                List.of(),
                true,   // renameClasses
                true,   // stringEncrypt
                false,  // aggressive
                false,  // max
                true,   // ultra
                false,  // insane
                false
        );

        ObfuscationResult result = obfuscate(config);

        assertTrue(Files.exists(output),
                "Output JAR must exist for variant " + variantId);

        assertNoClassParseErrors(output);
        assertAllClassesLoadable(output);
        assertNoVerifyParseErrors(result, variantId);
        printBugWarnings(result, "ultra/variant-" + variantId);
    }

    // =========================================================================
    // Test 4 – Insane mode
    // =========================================================================

    @ParameterizedTest
    @ValueSource(ints = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19})
    void allVariantsLoadAfterInsaneObfuscation(int variantId) throws Exception {
        Path input  = tempDir.resolve("in_"  + variantId + ".jar");
        Path output = tempDir.resolve("out_insane_" + variantId + ".jar");

        new RandomJarGenerator().generateVariant(variantId, input);

        // insane mode
        ObfuscationConfig config = new ObfuscationConfig(
                input, output,
                12345L,
                false,
                List.of(),
                true,   // renameClasses
                true,   // stringEncrypt
                false,  // aggressive
                false,  // max
                false,  // ultra
                true,   // insane
                false
        );

        ObfuscationResult result = obfuscate(config);

        assertTrue(Files.exists(output),
                "Output JAR must exist for variant " + variantId);

        assertNoClassParseErrors(output);
        assertAllClassesLoadable(output);
        assertNoVerifyParseErrors(result, variantId);
        printBugWarnings(result, "insane/variant-" + variantId);
    }

    // =========================================================================
    // Test 5 – Deterministic output across separate runs (same seed)
    // =========================================================================

    @Test
    void deterministicAcrossVariants() throws Exception {
        int[] variants = {0, 5, 10, 15};

        for (int variantId : variants) {
            Path input = tempDir.resolve("in_det_" + variantId + ".jar");
            new RandomJarGenerator().generateVariant(variantId, input);

            Path run1 = tempDir.resolve("det_run1_" + variantId + ".jar");
            Path run2 = tempDir.resolve("det_run2_" + variantId + ".jar");

            ObfuscationConfig cfg1 = new ObfuscationConfig(
                    input, run1,
                    42L, false, List.of(),
                    true, true, true, false, false, false, false
            );
            ObfuscationConfig cfg2 = new ObfuscationConfig(
                    input, run2,
                    42L, false, List.of(),
                    true, true, true, false, false, false, false
            );

            obfuscate(cfg1);
            obfuscate(cfg2);

            assertTrue(Files.exists(run1), "Run-1 output missing for variant " + variantId);
            assertTrue(Files.exists(run2), "Run-2 output missing for variant " + variantId);

            byte[] bytes1 = Files.readAllBytes(run1);
            byte[] bytes2 = Files.readAllBytes(run2);

            assertArrayEquals(bytes1, bytes2,
                    "Obfuscation is not deterministic for variant " + variantId
                            + " (seed=42, aggressive mode). "
                            + "Run-1 size=" + bytes1.length + ", Run-2 size=" + bytes2.length);
        }
    }

    // =========================================================================
    // Test 6 – No [VERIFY_PARSE_ERROR] across all variants in insane mode
    // =========================================================================

    @Test
    void noVerifyParseErrors() throws Exception {
        List<String> allErrors = new ArrayList<>();

        for (int variantId = 0; variantId < 20; variantId++) {
            Path input  = tempDir.resolve("in_vpe_"  + variantId + ".jar");
            Path output = tempDir.resolve("out_vpe_" + variantId + ".jar");

            new RandomJarGenerator().generateVariant(variantId, input);

            ObfuscationConfig config = new ObfuscationConfig(
                    input, output,
                    12345L,
                    false,
                    List.of(),
                    true, true, false, false, false, true, false
            );

            ObfuscationResult result = obfuscate(config);

            int finalVariantId = variantId;
            result.warnings().stream()
                    .filter(w -> w.contains("[VERIFY_PARSE_ERROR]"))
                    .map(w -> "variant-" + finalVariantId + ": " + w)
                    .forEach(allErrors::add);
        }

        if (!allErrors.isEmpty()) {
            fail("Found " + allErrors.size() + " [VERIFY_PARSE_ERROR] warning(s) across all variants "
                    + "in insane mode:\n" + String.join("\n", allErrors));
        }
    }

    // =========================================================================
    // Test 7 – Resources are preserved after obfuscation
    // =========================================================================

    @Test
    void obfuscatedJarContainsAllResources() throws Exception {
        Path input  = tempDir.resolve("in_res.jar");
        Path output = tempDir.resolve("out_res.jar");

        new RandomJarGenerator().generateVariant(0, input);

        ObfuscationConfig config = new ObfuscationConfig(
                input, output,
                42L,
                false,
                List.of(),
                true, true, true, false, false, false, false
        );

        obfuscate(config);

        assertTrue(Files.exists(output), "Output JAR must exist");

        try (JarFile jf = new JarFile(output.toFile())) {
            var entry = jf.getEntry("assets/test/variant.txt");
            assertNotNull(entry,
                    "Expected resource 'assets/test/variant.txt' was not found in the obfuscated JAR. "
                            + "Available entries: "
                            + jf.stream().map(java.util.jar.JarEntry::getName).toList());
        }
    }
}
